tokenizer_str: 'gpt2'
trainer:
  # moco_momentum: 0.995
  # moco_alpha: 0.4
  actual_vocab_size: 50257
optimizers:
  - lr: 6e-4
    # weight_decay: 1e-1
disable_flash: True
batch_size: 48
num_steps: 200
num_val_steps: 20
gradient_accumulation_steps: 1
# reset_moco_after_k_epochs: [1, 2]
epochs: 1
#precision: 'no', 'fp8', 'fp16', 'bfp16'
precision: 'fp16'
model:
  # chkpt_path: 'checkpoints/nano-mini-actual-ds-ecommerce-sparse.pt'
  use_cross_attn: True
  use_soft_prompting: True
  no_repeat_n_grams: [2, 3, 4, 5]
  vision_encoder_config:
    enable_gradient_checkpointing: True
    input:
      n_channels: 3
      width: 128
      height: 128
    n_layer: 12
    n_cls: 64
    num_patches: 16
    n_channels: 32
    feature_extractor_gate_sizes: [ 8, 16 ]
    feature_extractor_kernel_size: [ 6, 6 ]
    transformer_config:
      attn_config:
        attn_dropout: 0.1
        bias: False
        dropout: 0.1
        n_head: 8
        n_embd: 1024
        attn_type: multi_query
      max_block_size: 320  # (256 for input + 64 for cls)
      is_sparse_attn: True
      sparsity_factor: 0.5
      rotator_config:
        # ff_mult_factor * n_embed * n_embed params ->
        # 2 * num_experts * ff_mult_factor * n_embed * proj_features
        num_experts: 4
        proj_features: 16
        gate_sizes: [ 32 ]
        ff_mult_factor: 2
        top_k: 2
  decoder_config:
    enable_gradient_checkpointing: True
    n_layer: 12
    block_size: 256
    # 50257 (gpt2 tokenizer) + 1 special tokens for training <MSK>
    vocab_size: 50258   # 50257 + 1
    transformer_config:
      is_cross_attn: True
      attn_config:
        attn_dropout: 0.1
        bias: True
        dropout: 0.1
        n_head: 8
        n_embd: 1024
        attn_type: multi_query
      max_block_size: 320  # block size
      is_sparse_attn: True
      sparsity_factor: 0.5
      rotator_config:
        num_experts: 4
        proj_features: 16
        gate_sizes: [ 32 ]
        ff_mult_factor: 4
